### PR TITLE
add async test timeout

### PR DESCRIPTION
**Pull request by willingc**
Addresses #410 

- Increase ASYNC_TEST_TIMEOUT from default to 15 which is what we have been using for Tornado on JupyterHub tests
- Increase sleep to 10s

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks @willingc. These should fix it, but I think a better longer-term approach would be similar to #413:

1. Use 'kubectl rollout' to check when hub is ready, rather than listing pods
2. Make a HTTP request to hub and make sure it responds positively before moving on.

I'm happy to merge this as is too, since it'll fix the issues right now. Mid-to longer term we should do both the above things tor test-main too though.

**Comment by willingc** [comment]
@yuvipanda I think that we will likely need both this and #413. This one should help with the tests that use @pytest.gen while #413 should help with not starting until ready.

**Comment by yuvipanda** [comment]
@willingc oh yeah, I was only talking about the sleep, rather than the ASYNC_TIMEOUT.

**Comment by yuvipanda** [comment]
Going to merge this when tests pass unless you have objections!

**Comment by willingc** [comment]
Go for it @yuvipanda. I'm cool with removing the sleep 10 as well if you want. It was just giving a little extra margin.

**Comment by yuvipanda** [comment]
Thanks for the patch @willingc! I'm happy we're now treating all CI flakes seriously :)

**Pull request merged**
