### PR TITLE
improving docs explaining what binderhub is

### PR DESCRIPTION
**Pull request by choldgraf**
This attempts to reorganize the docs a little bit so that they group together more neatly, and also tries to improve the introductory information so we do a more complete job of explaining what BinderHub is doing under the hood.

### CODE REVIEW

**Comment by betatim** [comment]
Looks good to me. Merge?

**Comment by choldgraf** [comment]
Ready to go from my end!

**Comment by choldgraf** [comment]
@betatim ping :-)

**Comment by choldgraf** [comment]
fixed the merge conflict w/ a rebase....would appreciate somebody taking a look :-)

**Comment by willingc** [comment]
Thanks @choldgraf

**Pull request merged**
