### PR TITLE
Emit launch events

### PR DESCRIPTION
**Pull request by bitnik**
With this PR binder gets pending spawn (launch) events from jhub's progres api and sends them to bhub' UI.

First commit is copy of what @minrk showed to me during the workshop, thank you :)

### CODE REVIEW

**Comment by bitnik** [comment]
thanks for the review @minrk. I made the suggested change.

I also extended `test_build` function, so it counts `launching` events from spawner and checks if count is more than 2. But I am not sure about it.

**Comment by bitnik** [comment]
@minrk could you make a new review? I am not happy with the test I added, but I don't have a better idea now. I am open to get help :)

**Comment by consideRatio** [comment]
Hey @bitnik and @minrk! I'm going through various PRs hoping to help them resolve one way or another or perhaps get an updated description about the current status of things. What do you think about this PR?

**Comment by minrk** [comment]
I think we should absolutely do it, and I feel really bad to have dropped the review for so long. I'll take a stab at rebasing and resolving the conflicts and finishing it up.

**Comment by bitnik** [comment]
Thanks for taking it over and finishing it up! I am closing this PR :)

**Pull request closed without merging**
