### PR TITLE
Enable template extension

### PR DESCRIPTION
**Pull request by bitnik**
https://github.com/jupyterhub/binderhub/commit/6e194dde00f196edf31a095ef65572ac8c4db5df enables extension of base binder templates by supplying new templates under `template_path` and also adding new templates variables with `template_variables`.  `template_path` is where new templates are located. Base templates are loaded both with and without `templates/` prefix, so new templates can extend base templates by including `{% extends "templates/<template_name>.html" %}`, otherwise it overwrites the base template. An example configuration:
```bash
template:
  variables:
    var1: value1
    var2: value2
  path: /etc/binderhub/templates
```

I am not sure about https://github.com/jupyterhub/binderhub/commit/281b1cb2b172aed7f30847b2b1b9c187dff27de8. The idea was that users can supply extra static files to be used in new templates, so they are also served by binder app as other static files. To do that `extra_static_path` (where extra static files are located) must be defined and in templates source of extra static files must be defined as `"/<base_url>/<extra_static_url_prefix>/<static_file_path>"`. Do you think that this is a good idea?

related to https://github.com/jupyterhub/binderhub/issues/260
This PR is based on https://github.com/jupyterhub/jupyterhub/pull/1601

### CODE REVIEW

**Comment by bitnik** [comment]
To use this feature in a deployment, one has to first extend binderhub docker image by copying templates and static files as in this example:
```bash
FROM jupyterhub/k8s-binderhub:<tag>

COPY templates /etc/binderhub/templates
COPY static /etc/binderhub/static
```
And use this image in helm config.

I was thinking how to get rid of this step. Maybe we could find a solution by using gitRepo volume or [initContainers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) to clone/download these files and mount to a specified path where binder app looks for them?

**Comment by minrk** [comment]
This is really great! If you can come up with an example that uses a volume without rebuilding the image, that would be pretty cool

**Comment by bitnik** [comment]
@minrk https://github.com/jupyterhub/binderhub/pull/545/commits/51cddfd9fd894c22bb43e5300641e9dabf617885 enables `initContainers`, `extraVolumes` and `extraVolumeMounts` configuration in binder deployment. By using them, templates and static files can be added into a volume and don't need to rebuild the image. Here is an example configuration:

```yaml
template:
  path: "/etc/binderhub/templates/<path_to_templates_in_repo>"
  static:
    path: "/etc/binderhub/templates/<path_to_static_files_in_repo>"
    urlPrefix: extra_static/

initContainers:
  - name: git-clone-templates
    image: alpine/git
    args:
      - clone
      - --single-branch
      - --branch=<branch_name>
      - --
      - <repo_url>
      - /etc/binderhub/templates
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: custom-templates
        mountPath: /etc/binderhub/templates
extraVolumes:
  - name: custom-templates
    emptyDir: {}
extraVolumeMounts:
  - name: custom-templates
    mountPath: /etc/binderhub/templates
```

**Comment by minrk** [comment]
Very nice!

**Pull request merged**
