### PR TITLE
Image Optimization

### PR DESCRIPTION
**Pull request by vardaan-raj**
I have simply compressed the size of the images without compromising their quality, to make them more space-efficient

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks a lot for opening this, @vardaan-raj! I see a bunch of PNG files had been removed. Is this intentional?

Also can you mention what program you used to compress these?

**Comment by vardaan-raj** [comment]
I have used Img-Bot to compress them. You can read more about it here

https://imgbot.net/docs/

**Comment by vardaan-raj** [comment]
I'm not sure about any removed images , I have just tried to optimize the images,  I haven't deleted or altered anything else....

**Comment by yuvipanda** [comment]
If you look at https://github.com/jupyterhub/binderhub/pull/1349/files, the bot seems to have removed a bunch of png files.

**Comment by minrk** [comment]
@yuvipanda the UI is a bit confusing for binary files significantly reduced in size - the files aren't deleted, but much of their *contents* are decreased, e.g.

Screen Shot 2021-09-17 at 09 11 28

**Comment by yuvipanda** [comment]
Aaah, ok! Thanks for pointing that out, @minrk. And thanks for the PR, @vardaan-raj!

**Pull request merged**
