### PR TITLE
breaking: require Python 3.8, from Python 3.6

### PR DESCRIPTION
**Pull request by consideRatio**
- breaking: require Python 3.8, from Python 3.6
- pre-commit: run with pyupgrade --py38-plus

### CODE REVIEW

**Comment by manics** [comment]
Do you mind adding this breaking change to https://github.com/jupyterhub/binderhub/blob/main/CHANGES.md#breaking-changes ?

**Comment by manics** [comment]
On second thoughts, let's leave the breaking changes doc till after all these breaking PRs are merged to avoid dealing with conflicts.... just need to remember :smile:

**Review by manics — APPROVED** [review]
Go ahead and merge if you're happy with the CI

**Comment by consideRatio** [comment]
> On second thoughts, let's leave the breaking changes doc till after all these [breaking](https://github.com/jupyterhub/binderhub/labels/breaking) PRs are merged to avoid dealing with conflicts...

Yepp I was thinking the same thing!

Thanks for your review!!

**Comment by ofek** [comment]
Hello! Just FYI now that 3.6 is no longer supported Hatchling can be used as the build backend. cc @blink1073 to confirm

**Comment by blink1073** [comment]
Yes, that is true, using `hatch-jupyter-builder`'s migration [script](https://github.com/jupyterlab/hatch-jupyter-builder#migration).

**Pull request merged**
