### PR TITLE
Add 'origin' field to launch events

### PR DESCRIPTION
**Pull request by yuvipanda**
Lets us differentiate launches from different BinderHub
installations

### CODE REVIEW

**Comment by betatim** [comment]
Looks good.

Do you think we need some normalising capabilities or will need them? For example the OVH cluster can be reached via multiple hostnames, should we let the operator of the hub configure how to normalise those (into one hostname?)? I'm tending towards "no".

**Comment by yuvipanda** [comment]
@betatim hmm, that's a good point actually. I think it might be a good idea to allow that - especially if we want to not expose the hostnames to end users. That'll futz with `self.request.host`.

**Comment by yuvipanda** [comment]
@betatim updated

**Pull request merged**
