### PR TITLE
[MRG] Update dockerd version used for DIND

### PR DESCRIPTION
**Pull request by betatim**
Upgrade from 18.x to 19.x for the dockerd we use for DIND.

Keeping current is probably a good thing.

### CODE REVIEW

**Comment by betatim** [comment]
I kind-of tested this on a local deployment with minikube and DIND. It successfully builds the minimal dockerfile example from binder-examples but for the "requirements" example it fails on the  third step with `E: You don't have enough free space in /var/cache/apt/archives/.`. I think this is an artefact of using DIND in minikube.

Unless someone knows a reason why this shouldn't work I'd suggest we merge and deploy it and see what happens.

**Comment by consideRatio** [comment]
I recall an increased security requirement or something like that regarding certificates in communication, if it works at all then im +1 because if that was an issue we would know quickly i think.

**Comment by betatim** [comment]
I think we side step the certificates-by-default (which is indeed in the release notes/I saw it somewhere) topic because we explicitly set the docker socket to be a socket file, not TCP. If it is broken at such a fundamental level I think even a basic build wouldn't have worked on minikube (and will fail on staging).

**Comment by choldgraf** [comment]
LGTM - thanks for the bump!

**Pull request merged**
