### PR TITLE
Upgrade xterm to newer version

### PR DESCRIPTION
**Pull request by yuvipanda**
- Remove null-loader hack to keep old xterm working with
  newer version of webpack
- Remove vendored older version of xterm fit addon

Refinement of https://github.com/jupyterhub/binderhub/pull/1248

Co-authored-by: Kenan Erdogan <kenanerdogan@gmail.com>

### CODE REVIEW

**Comment by yuvipanda** [comment]
image

feels good

**Review by consideRatio — APPROVED** [review]
I'm not feeling fit to review this properly, but I'd say go for it. I feel we must manage to keep things a bit better updated, and this is a small chunk PR towards that.

**Comment by yuvipanda** [comment]
ya hopefully we can try dependabot or something of that sort for js dependencies? But this is a biggish bump, hopefully future bumps are easier.

**Comment by betatim** [comment]
Has one of you tested this locally to see if it still works in the various cases that it is used?

**Comment by yuvipanda** [comment]
@betatim yeah I did.

**Comment by consideRatio** [comment]
@yuvipanda I ended up causing a merge conflict in this after merging another PR of yours. I'd press merge if this wasn't for that or if I was confident enough to solve the conflict myself.

**Comment by yuvipanda** [comment]
@consideRatio i've fixed the conflict!

**Pull request merged**
