### PR TITLE
bump jupyterhub chart

### PR DESCRIPTION
**Pull request by minrk**
get changes that should help reduce orphaned pods

### CODE REVIEW

**Comment by yuvipanda** [comment]
This is unfortunately not enough. There has been a breaking change in the
Jupyterhub chart related to how ingresses are specified that needs changing
too. Can someone revert this for now? I'm on my phone...

**Comment by choldgraf** [comment]
reverted just to be on the conservative side

**Comment by willingc** [comment]
Out of curiosity...what was the breaking change on our side or k8s? If ours, how can I tell from the chart history.

**Comment by yuvipanda** [comment]
@willingc it was broken in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/229 and I added it to the changelogs in - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/249/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR42. I should've opened an issue here though, which I didn't :(

In the future, we should probably be writing the CHANGELOG as we go, which would help spot these things. Does that sound like an answer to the latter half of your question?

**Comment by willingc** [comment]
Thanks @yuvipanda. It didn't occur to me to look at the still open changelog. I only cross scanned recently merged PRs. No worries on the issue opening.

Not sure re: CHANGELOG since it didn't occur to me to look there. Yet, it seems like a good idea.

**Pull request merged**
