### PR TITLE
JS & CSS: Autoformat with pre-commit & prettier

### PR DESCRIPTION
**Pull request by yuvipanda**
I removed the two lines in `.pre-commit-config.yaml` and ran `pre-commit run -all`

Follow-up to https://github.com/jupyterhub/binderhub/pull/1761

### CODE REVIEW

**Comment by consideRatio** [comment]
@yuvipanda can you push the changes you make manually in a dedicated commit?

**Comment by yuvipanda** [comment]
@consideRatio I didn't make any manual changes here, unless you're talking about the changes to `.pre-comit-ci.yaml`?

**Comment by yuvipanda** [comment]
I edited the description to describe what I did.

**Comment by yuvipanda** [comment]
no idea why eslint now fails though. I'll investigate later.

**Comment by yuvipanda** [comment]
Given I'm making some more fixes to the JS, I'm actually going to come back to this later. I think trying to fix this right now will 100% sap the 'fix things' energy I have.

**Pull request closed without merging**
