### PR TITLE
WIP: Improve User Interface to allow selection of interface

### PR DESCRIPTION
**Pull request by rgaiacs**
Related to jupyterhub/binderhub#799.

Screenshot from 2019-03-18 15-20-11

Future work:

- [ ] Integrate Javascript

### CODE REVIEW

**Comment by consideRatio** [comment]
Woooo oh I think this is very relevant UX improvement! :heart: @rgaiacs :heart:

**Comment by betatim** [comment]
I think we need to keep the UI element for setting the `urlPath` parameter "by hand" as it is used to do all sorts of things in addition to selecting between the possible UIs we can list.

Maybe the way forward is to create two views of this launch form. The default one would show a simplified view that focusses on "I am a user and these are the goals I want to achieve" (for example selecting a UI from a premade dropdown selection). A "advanced" or "expert" one which shows things from the view we currently have "urlPath" and "filePath" etc that let you set them to what ever value you want but also require you to know what they do and how they interact etc.

**Comment by rgaiacs** [comment]
@betatim I like the idea of simplified vs "advanced". I can devote a few hours on 3rd April to work on this.

**Comment by betatim** [comment]
Sounds great. If someone else has time before then are you Ok with them creating a PR for that?

**Comment by rgaiacs** [comment]
> If someone else has time before then are you Ok with them creating a PR for that?

Absolutely! Anyone is welcome to take over this PR. :heart:

**Comment by drj11** [comment]
why bother with the "advanced" version? Document the URL structure and advanced users can splice the URL together themselves.

**Comment by betatim** [comment]
> why bother with the "advanced" version?

because even expert users enjoy a bit of UI candy to help them to what they want to do.

**Comment by drj11** [comment]
yes, with infinite budget, of course.

**Comment by consideRatio** [comment]
Hey @rgaiacs! I'm going through various PRs hoping to help them resolve one way or another or perhaps get an updated description about the current status of things. What do you think about this PR?

The current ui looks like this.

Screenshot from 2021-09-23 01-38-40

Is it really worth having a choice of UIs? I'm thinking it could indicate to the user that the listed UIs will be available, which the binderhub UI can't really say. Currently we count on JupyterLab to be available and have a fallback to Jupyter Notebook after #1383 is merged.

**Comment by rgaiacs** [comment]
Hey @consideRatio! Thanks reaching out.

This pull request was open during one event organised by [The Turing Way](https://the-turing-way.netlify.app/welcome). We were using R Studio from Binder and I wanted to open an R project with Jupyter Notebook.

I'm happy for you to close this pull request based in that Binder can't upfront which UI will be available and users requesting an unavailable UI will lead to poor user experience.

**Comment by consideRatio** [comment]
Thanks for the quick response @rgaiacs! I'll go ahead with a close then.

One thing I take with me going onwards is that it would be valuable if we could do some inspection work of built repo's or similar, as such data could be used to enable features like this in a reliable way.

Thank you for being an active member of the community @rgaiacs! :heart:

**Pull request closed without merging**
