### PR TITLE
[MRG] Check if nbviewer URL would show an error

### LINKED ISSUE #922: 404 page shown during build when pointing to a repo
I have a binder repo [here](https://github.com/davidanthoff/teaching-2019-aere-workshop/tree/v1.0.1). When people click on the "Launch binder" button, they see this:

image

Which is really not ideal because then they think that something went wrong and that there is some bug, when in fact everything is fine.

I think the reason it looks that way is that I'm actually not linking to a specific notebook, but instead just to the whole repo. I think in that case it would be better to not show a 404 link during build, but something that looks less scary and that doesn't look like something went wrong.

EDIT: This was originally posted over in the repo2docker repo as https://github.com/jupyter/repo2docker/issues/761, but @betatim asked me to move it here. He also pointed out a workaround over there, which I have since implemented in my repo. So the link in this issue here now points to an old version of the repo that has the old type of link. While the workaround is great, I think it would be great if things worked without it.

### PR DESCRIPTION
**Pull request by betatim**
If the nbviewer widget would show a 404 or other error we don't want to
display it. We check the status before rendering the template by making
a HEAD request to nbviewer, if the status code is >=400 we don't show
the preview.

closes #922

### CODE REVIEW

**Comment by betatim** [comment]
@lesteve I only saw [your comment](https://github.com/jupyterhub/binderhub/issues/816#issuecomment-522847777) after making this PR. Sorry :-/

This implements your idea using the tornado HTTP client instead of urllib. The code has to work async/non-blocking and I don't think urllib supports that (yet).

It isn't quite the feature requested in #816 because it doesn't give the choice of disabling or not to the user. However this is a quick win, we can still add the "disable even if the preview works" options if we decide we want that.

**Comment by lesteve** [comment]
Very nice to see this, thanks a lot!

No worries about superseding my naive attempt. I got binder setup locally using minikube and learned a few useful things along the way!

**Comment by lesteve** [comment]
Very nice to see this merged! Naive question: I assume I have to monitor the commits in https://github.com/jupyterhub/mybinder.org-deploy in particular the changes in [values.yaml](https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/values.yaml) (I have read the blog post https://blog.jupyter.org/automating-mybinder-org-dependency-upgrades-in-10-steps-bb5e38542059).

Are there additional steps I need to be aware of until this change reach mybinder.org.

Note: I am not in a hurry at all, I am asking out of curiosity and to have some very rough estimate when I can give this a whirl on mybinder.org.

**Comment by betatim** [comment]
We have a bot (henchbot, just referenced this PR) that opens a PR on the deploy repo. The bot runs about once an hour and usually(depends on where people are, if it is night, weekend, etc) someone clicks merge an hour or two after the bot opened the deploy PR. Then it is live!

**Comment by lesteve** [comment]
OK that matches what I understood from the blog post, thanks for confirming this!

**Pull request merged**
