### PR TITLE
pydata theme

### PR DESCRIPTION
**Pull request by choldgraf**

### CODE REVIEW

**Comment by choldgraf** [comment]
(if nobody gets to it first, I'll self-merge this since our docs are broken until it gets merged)

**Comment by betatim** [comment]
The Travis failure looks unrelated. I think something with docker has changed on travis. Also seeing errrors on https://travis-ci.org/github/jupyter/repo2docker/jobs/665418991 which really shouldn't be erroring

**Comment by betatim** [comment]
Did you investigate why travis failed?

**Comment by consideRatio** [comment]
@betatim i saw errors and presumed they were either temporary or unrelated as this PR modifies doc/doc-requirements.txt and doc/conf.py to fix broken documentation.

I'll open a new issue to represent this issue, as it seems consistently broken.

**Comment by consideRatio** [comment]
It was the same test failing, i opened a new issue for it: https://github.com/jupyterhub/binderhub/issues/1080

**Pull request merged**
