### PR TITLE
[MRG] Make different repo providers accessible via the UI

### PR DESCRIPTION
**Pull request by betatim**
Getting started on making other repo providers accessible from the UI.

This is what it currently looks like:
repo-providers

### CODE REVIEW

**Comment by betatim** [comment]
I think this is good for some reviewing now. The JS is getting pretty ugly/duplicated :-/

repo-providers2

**Comment by minrk** [comment]
Tested locally and it works great!

**Comment by choldgraf** [comment]
how'd I miss this?! cool!

to be clear, this is *just* the UI right? We still don't support a `/v2/gl` request?

**Comment by betatim** [comment]
This is super cool, not just cool because we have supported `/v2/gl/...` for a while now so this adds the missing piece to make it user friendly :)

**Comment by choldgraf** [comment]
really?! man I am behind the times

**Pull request merged**
