### PR TITLE
Issue 237 use github credentials and pass to repo2docker

### LINKED ISSUE #237: Accessing private GitHub repositories
I managed to setup BinderHub by following the steps described in the manual. However, naturally, I cannot reach repositories stored in my organization's directory (private ones). Is there any HOWTO configure the deployment to be able to access GitHub restricted parts?

### PR DESCRIPTION
**Pull request by zymergen-luke**
This is an expansion upon https://github.com/jupyterhub/binderhub/pull/408 and fixes  #237

It contains three changes:
1. fix invalid reference to `provider.git_credential` (to `self.git_credentials`)
2. Renames `git_credential` -> `git_credentials` to be more in line with usage elsewhere in codebase
3. Adds support for using personal access token login (if clientId is specified in addition to an access_token)

In total it will connect to github (using either an oauth token or personal access token) and pass those credentials to repo2docker. Combined with changes in repo2docker to respect git credentials (https://github.com/jupyter/repo2docker/commit/8195bbc32465334a15bb2e34267bcb474fcc13c3) we have a working end-to-end solution for private github repos.

### CODE REVIEW

**Comment by betatim** [comment]
Travis is unhappy because of your renaming of one of the arguments.

Could you add a small test to check that the credentials arrive as expected and that mechanism doesn't get broken in the future?

**Comment by zymergen-luke** [comment]
It looks like a bad merge - the parameter was renamed to repo_url on master, but didn't propogate into my branch fully.

I added a unit test for Build to ensure that when the pod is submitted that any credentials passed to the build are included in the environment.

**Comment by betatim** [comment]
Merged! Congrats to your first merged PR on repo2docker 🎉

**Comment by choldgraf** [comment]
wooooo nicely done! This is a super useful feature!

**Pull request merged**
