### PR TITLE
[MRG] GitHub actions badge in README

### PR DESCRIPTION
**Pull request by consideRatio**
- __rST to Markdown conversion of README.md__
  I hope this is found to be okay, it matters to me.
- __CI badge updated__
  Travis badge replaced with github actions badge.

### CODE REVIEW

**Review by betatim — CHANGES_REQUESTED** [review]
Please make a separate PR for changing the format of the README and one for the GitHub Action changes.

I would have merged the badge update but the other two changes need reviewing and discussion.

**Comment by consideRatio** [comment]
@betatim done, see #1216

**Review by betatim — COMMENTED** [review]
Do you know why the readme is a rst at the moment? Before changing it we should find out if there was a reason and if it still applies.

**Comment by ctb** [comment]
> Do you know why the readme is a rst at the moment? Before changing it we should find out if there was a reason and if it still applies.

I don't know why, but one plausible reason is that Once Upon a Time, PyPI didn't support Markdown. (Many of my projects suffered from the same problme.) It does now,
and this PR adjusts setup.py to upload it properly, too!

**Comment by betatim** [comment]
Thanks for the history lesson :)

**Pull request merged**
