### PR TITLE
serving favicon

### PR DESCRIPTION
**Pull request by choldgraf**
I noticed the favicon wasn't being served from its spot...this is a semi-blind attempt at getting this to work. Tell me if I'm totally doing this wrong :-)

### CODE REVIEW

**Comment by yuvipanda** [comment]
Testing with this patch, I get a 404 with the following contents on hitting `/favicon.cio`:

```
Traceback (most recent call last):
  File "/home/yuvipanda/code/binderhub/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
    result = yield result
  File "/home/yuvipanda/code/binderhub/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/yuvipanda/code/binderhub/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/yuvipanda/code/binderhub/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/yuvipanda/code/binderhub/lib/python3.6/site-packages/tornado/web.py", line 2358, in get
    self.root, absolute_path)
  File "/home/yuvipanda/code/binderhub/lib/python3.6/site-packages/tornado/web.py", line 2549, in validate_absolute_path
    raise HTTPError(404)
tornado.web.HTTPError: HTTP 404: Not Found
```

**Comment by choldgraf** [comment]
hmmm.....

**Comment by minrk** [comment]
Not at all obvious, but `/favicon.ico` is served by the default tornado static handler and should be in the `binderhub/static/favicon.ico`. It should work there without any additional handlers. Same goes for `robots.txt`, it turns out.

I'me surprised that this custom handler didn't take precedence, but 🤷‍♀️

**Comment by choldgraf** [comment]
so does the latest commit fix it then? @minrk ?

**Comment by minrk** [comment]
Yup!

**Comment by yuvipanda** [comment]
@minrk @choldgraf can one of you get this deployed? :)

**Pull request merged**
