### PR TITLE
added  Authorization header if access_token provided

### PR DESCRIPTION
**Pull request by kaseyhackspace**
This fixes issue https://github.com/jupyterhub/binderhub/issues/952 by adding an `Authorization: token <access_token>` header to Github API requests from Binderhub if access_token is passed by either `binderhub_config.py` or `GithubRepoProvider` in `secret.yaml`.

### CODE REVIEW

**Comment by betatim** [comment]
Thanks for the PR!

I think @sgibson91 has been looking into this as well so getting your input here would be great. I've never even tried to use the features of a BinderHub for "private" deployments so don't have a good feeling if this would break other things or if it should have been solved some other way.

**Comment by betatim** [comment]
This change seems to have broken one of the tests [here](https://travis-ci.org/jupyterhub/binderhub/jobs/585671406#L3135-L3155) (sorry for the very verbose output of our CI).

**Comment by betatim** [comment]
There is also https://github.com/jupyterhub/binderhub/pull/940 to look at/compare to/check with.

**Comment by kaseyhackspace** [comment]
> This change seems to have broken one of the tests [here](https://travis-ci.org/jupyterhub/binderhub/jobs/585671406#L3135-L3155) (sorry for the very verbose output of our CI).
@betatim  I was actually looking into this, and it seems to be a weird point of failure from the CI test. The failure is from a null result of getting gitlab `ref`. The code changes I made were inside the class `GitHubRepoProvider` which should not be related to `GitlabRepoProvider`.

Is there a way to re-trigger the travis-ci tests?

**Comment by betatim** [comment]
You think this is a flakey test? I restarted it now. I thought it was related to the change because something in the GitLab provider broke.

**Comment by kaseyhackspace** [comment]
> You think this is a flakey test? I restarted it now. I thought it was related to the change because something in the GitLab provider broke.

Looked more into this and the failure was also the same as PR https://github.com/jupyterhub/binderhub/pull/951so I looked at the actual test. I think we are getting failures because the repository we are testing against was updated from  `gitlab-ce` to `gitlab-foss`. I did another branch on my fork with an updated repo name and tried a PR there. Waiting for the test to finish to see if that fixes that issue. Will keep you updated here 😄

**Comment by kaseyhackspace** [comment]
@betatim  so the ci tests have finished for the new branch I made that rectified the `test_gitlab_ref` case that was failing and it is now passing (https://travis-ci.com/kaseyhackspace/binderhub/jobs/236599088#L3086). This branch should fix both this PR and the error in PR https://github.com/jupyterhub/binderhub/pull/951. Question now is, how do we proceed:
- Do I PR the branch (https://github.com/kaseyhackspace/binderhub/tree/update-test-repoproviders) to `jupyterhub/binderhub`'s `master`?
- should I merge and push the branch to this current PR?

**Comment by betatim** [comment]
Ah, I just opened #956 to fix the failure after looking at a different PR (but not this one) during my morning coffee. Sorry for the double effort. If you could take a quick look at #956 and leave a review we could merge that. After that I'd rebase this PR and #951 onto `master`.

**Comment by kaseyhackspace** [comment]
> Ah, I just opened #956 to fix the failure after looking at a different PR (but not this one) during my morning coffee. Sorry for the double effort. If you could take a quick look at #956 and leave a review we could merge that. After that I'd rebase this PR and #951 onto `master`.

It's all good @betatim , it's never a wasted effort 😄 https://github.com/jupyterhub/binderhub/pull/956 is good to merge.

**Pull request merged**
