### PR TITLE
Update logos in docs

### PR DESCRIPTION
**Pull request by choldgraf**
This updates the logo in the new alabaster theme to the Binder logo.

That said, we haven't had a conversation about whether we want it to be the **Binder** logo, or the **Jupyter** logo. I lean towards the Binder logo to avoid confusion for people who arrive there from the `mybinder` docs. However I think we should come to a community agreement on this.

If we do want the Jupyter logo, I'll switch the logo to use the SVG+favicon that's currently in the repo2docker documentation. Here's a link to the built docs:

http://predictablynoisy.com/binderhub/

What do you all think?

### CODE REVIEW

**Comment by betatim** [comment]
screen shot 2017-10-25 at 23 42 06


Renders nicely for me. Big 👍 for providing the link to the rendered docs!

Can binder have a custom Jupyter logo like jupyterhub has? You know as the weird compromise that no one really likes :-/

**Comment by choldgraf** [comment]
I created a weird hybrid a while back where the orange circle was actually the jupyter logo ring thingies, but I think people thought it looked weird haha

**Comment by betatim** [comment]
Merge?

**Comment by choldgraf** [comment]
let's wait to see what others think, @willingc has a better feel than I do about branding/logos/etc...what do you think carol?

**Comment by Carreau** [comment]
+1, and as @willingc is taking some time of I think we can merge without waiting. It's always easy to revert !

**Comment by willingc** [comment]
@choldgraf @yuvipanda @betatim @Carreau Looks good. Just an FYI, I'm on vacation until Thurs Nov 2. Merge away. :tada:

**Pull request merged**
