### PR TITLE
document how to use docker hub registry

### LINKED ISSUE #486: Using a non-gcr.io registry
We should document how to use a registry other than `gcr.io`. I think giving DockerHub as an example should suffice here. From the suggestion that @willingc gave, I believe we need to tell people how to fill in this part of the chart:

https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/values.yaml#L26

With the right values for DockerHub. In particular, we also need to give context for what this "JSON authentication" is which I believe is explained here:

https://docs.docker.com/engine/reference/commandline/login/#privileged-user-requirement

does this look correct?

cc @minrk

### PR DESCRIPTION
**Pull request by bitnik**
Hi, after https://github.com/jupyterhub/binderhub/pull/499, I also want to document how to use docker hub registry.

I was not sure where to document it exactly, so I just made an extra file for it. I can update it according to your feedback.

This is related to https://github.com/jupyterhub/binderhub/issues/486.

* closes #486

### CODE REVIEW

**Comment by choldgraf** [comment]
This looks great - I think it'd actually be better to have a separate page for creating a registry, and then have sub-sections for `gcr.io` vs. `dockerhub`. Could I make a push to your branch that does this?

**Comment by bitnik** [comment]
Nice, I just sent you an invitation.

**Comment by choldgraf** [comment]
ok, made a few rearrangements and edits so that both registries are in-line with one another. Can somebody else take a look at this to make sure it makes sense? @willingc ?

**Comment by choldgraf** [comment]
thanks for the docs update @bitnik !!! Super helpful!

**Pull request merged**
