### PR TITLE
[WIP] dev instructions for GKE cluster

### PR DESCRIPTION
**Pull request by choldgraf**
instructions for setting up a development version of binderhub, ping @yuvipanda

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks @choldgraf.

Things we need to still do:

1. Get a service account + token for accessing the container registry
2. Create a jupyterhub that works for binderhub in the remote cluster
3. Feed the  URL of this remote cluster on to binderhub_config.py
4. Create a new binderhub_config.py that works for this.

**Comment by choldgraf** [comment]
I wanna try finishing this up but the docs have changed quite a bit. @yuvipanda is this PR still necessary or have we addressed the same problems through other PRs etc? We should either close this or I should pick it back up and get it merged

**Comment by choldgraf** [comment]
@yuvipanda I feel like this is stale enough that we should probably just close it and have an issue open for it instead of a PR. I don't have time to work on this any time soon most likely...WDYT?

**Comment by willingc** [comment]
Let's go ahead and close the PR and open an issue. I may get to it next week.

**Comment by choldgraf** [comment]
ok :-)

**Comment by choldgraf** [comment]
https://github.com/jupyterhub/binderhub/issues/426

**Pull request closed without merging**
