### PR TITLE
Don't pause spinner when code is just loading slowly

### PR DESCRIPTION
**Pull request by yuvipanda**
Instead, pause it when launch actually fails

Ref #433

### CODE REVIEW

**Comment by choldgraf** [comment]
I think @Carreau should comment on this one - the reason the change was made was in order to avoid using too much CPU, which he was concerned about

**Comment by yuvipanda** [comment]
Updated wording, @betatim

**Comment by yuvipanda** [comment]
If the spinner is taking up too much CPU, IMO we should remove the spinner or fix it. I think currently it is making mybinder.org look much more unstable than it is, which makes for a very sad panda.

**Comment by Carreau** [comment]
Let's remove the timeout (for now), and try to add a metric for "after how long does a user leave the page if it's not launching".

That would give us some measure of what could be reasonable for an alternative UI or timeout.

We can also stop the spinner when the windows loose focus.

Infinite animation on the web sucks.

**Comment by choldgraf** [comment]
stopping the animation when the window looses focus after the timeout seems like a good compromise to me, though I think it we should leave that for another PR...merging!

**Pull request merged**
