### PR TITLE
pre-commit: let prettier format .js files

### PR DESCRIPTION
**Pull request by consideRatio**
A one line change in pre-commit-config -> autoformatting made by pre-commit.ci.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Yep, let's wait for the one I currently have brewing and then we can merge this. Will definitely help me avoid merge conflicts.

Thanks @consideRatio

**Comment by consideRatio** [comment]
> let's wait for __the one__ I currently have brewing and then we can merge this

This was #1771 that is now merged I think

**Comment by yuvipanda** [comment]
@consideRatio nope, there's one more coming (#1771 was a part of it).

**Comment by yuvipanda** [comment]
Actually let's just do this, I can rebase. Thanks @consideRatio

**Pull request merged**
